worker_processes 1;

error_log /opt/homebrew/var/log/nginx/error.log;
pid /opt/homebrew/var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /opt/homebrew/etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /opt/homebrew/var/log/nginx/access.log;

    sendfile on;
    keepalive_timeout 65;

    upstream backend_pool {
        server 10.3.3.71:3001;
        server 10.3.3.104:3002;
    }

    # Existing HTTP service
    server {
        listen 8080;
        server_name app.teamX.test api.teamX.test 10.3.3.178;

        location / {
            proxy_pass http://backend_pool;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # New HTTPS service
    server {
        listen 443 ssl;
        server_name app.teamX.test api.teamX.test;

        ssl_certificate /Users/kavyamukhija/Desktop/CN-Private-Network-Platform/tls/server.crt;
        ssl_certificate_key /Users/kavyamukhija/Desktop/CN-Private-Network-Platform/tls/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://backend_pool;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
